swagger: '2.0'
info:
  version: '1.0'
  title: "bookmark-service"
  description: Lambda-based microservice to store lists of hyperlinks 2
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json

paths:

  /bookmark:
    post:
      description: "Create a new bookmark"
      summary: "Create a new bookmark"

      x-amazon-apigateway-request-validators:
        basic:
          validateRequestParameters: true
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostLambdaFunction.Arn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
        responses: {}

      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Bookmark'

      responses:
        200:
          description: "Success"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        500:
          description: "Internal Server Error"

  /bookmark/{title}:
    get:
      summary: Get a bookmark
      description: Get a bookmark

      x-amazon-apigateway-request-validators:
        basic:
          validateRequestParameters: true
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetLambdaFunction.Arn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "GET"
        type: "aws_proxy"
        responses: {}

      parameters:
        - name: "title"
          in: "path"
          description: "Title of bookmark to return"
          required: true
          type: "string"
      responses:
        200:
          description: Successful Response
          schema:
            type: object
            items:
              $ref: '#/definitions/Bookmark'
          examples:
            application/json:
              - title: 'cool-programming-links'
                links:
                  - title: 'Google home page'
                    link: "https://google.com"
                  - title: 'Typescript is cool'
                    link: "https://typescript.io"

definitions:
  Bookmark:
    title: Bookmark
    type: object
    properties:
      title:
        type: string
      links:
        type: array
        items:
          $ref: '#/definitions/Link'
  Link:
    title: Link
    type: object
    properties:
      title:
        type: string
      url:
        type: string

